theme: jekyll-theme-minimal
title: Andrew Sverdrup
description: Mobile app dev ğŸ’», surfing ğŸ„â€â™‚ï¸, working out ğŸ’ªğŸ», basketball ğŸ€</br>Email: <a href="mailto:andrew@sverdrup.dev">andrew@sverdrup.dev</a>
logo: /assets/img/andrew-sverdrup.png
show_downloads: false
google_analytics: G-TBR8SHVDHZ
